from network.enums import Enum


__all__ = ['PhysicsType', 'EvaluationState', 'CameraMode', 'MovementState', 'AIState', 'Axis', 'CollisionGroups',
           'AnimationMode', 'AnimationBlend', 'CollisionState', 'InputButtons', 'AudioDistanceModel', 'ButtonState',]


def power_2_numbering(i):
    return 2 ** i


class PhysicsType(Enum):
    """Enum of Physics Types"""
    static = ...
    rigid_body = ...
    soft_body = ...
    no_collision = ...


class EvaluationState(Enum):
    success = ...
    failure = ...
    running = ...
    ready = ...


class CameraMode(Enum):
    first_person = ...
    third_person = ...


class MovementState(Enum):
    run = ...
    walk = ...
    static = ...


class AIState(Enum):
    idle = ...
    alert = ...
    engage = ...


class Axis(Enum):
    x = ...
    y = ...
    z = ...


class CollisionGroups(Enum, autonum=power_2_numbering):
    geometry = ...
    pawn = ...
    projectile = ...
    navmesh = ...


class CollisionState(Enum):
    started = ...
    ended = ...


class AnimationMode(Enum):
    play = ...
    loop = ...
    ping_pong = ...


class AnimationBlend(Enum):
    interpolate = ...
    add = ...


class ListenerType(Enum):
    action_in = ...
    action_out = ...
    state = ...


class InputButtons(Enum):
    ACCENTGRAVEKEY = ...
    AKEY = ...
    BACKSLASHKEY = ...
    BACKSPACEKEY = ...
    BKEY = ...
    CAPSLOCKKEY = ...
    CKEY = ...
    COMMAKEY = ...
    DELKEY = ...
    DKEY = ...
    DOWNARROWKEY = ...
    EIGHTKEY = ...
    EKEY = ...
    ENDKEY = ...
    ENTERKEY = ...
    EQUALKEY = ...
    ESCKEY = ...
    F10KEY = ...
    F11KEY = ...
    F12KEY = ...
    F13KEY = ...
    F14KEY = ...
    F15KEY = ...
    F16KEY = ...
    F17KEY = ...
    F18KEY = ...
    F19KEY = ...
    F1KEY = ...
    F2KEY = ...
    F3KEY = ...
    F4KEY = ...
    F5KEY = ...
    F6KEY = ...
    F7KEY = ...
    F8KEY = ...
    F9KEY = ...
    FIVEKEY = ...
    FKEY = ...
    FOURKEY = ...
    GKEY = ...
    HKEY = ...
    HOMEKEY = ...
    IKEY = ...
    INSERTKEY = ...
    JKEY = ...
    KKEY = ...
    LEFTALTKEY = ...
    LEFTARROWKEY = ...
    LEFTBRACKETKEY = ...
    LEFTCTRLKEY = ...
    LEFTMOUSE = ...
    LEFTSHIFTKEY = ...
    LINEFEEDKEY = ...
    LKEY = ...
    MIDDLEMOUSE = ...
    MINUSKEY = ...
    MKEY = ...
    MOUSEX = ...
    MOUSEY = ...
    NINEKEY = ...
    NKEY = ...
    OKEY = ...
    ONEKEY = ...
    OSKEY = ...
    PAD0 = ...
    PAD1 = ...
    PAD2 = ...
    PAD3 = ...
    PAD4 = ...
    PAD5 = ...
    PAD6 = ...
    PAD7 = ...
    PAD8 = ...
    PAD9 = ...
    PADASTERKEY = ...
    PADENTER = ...
    PADMINUS = ...
    PADPERIOD = ...
    PADPLUSKEY = ...
    PADSLASHKEY = ...
    PAGEDOWNKEY = ...
    PAGEUPKEY = ...
    PAUSEKEY = ...
    PERIODKEY = ...
    PKEY = ...
    QKEY = ...
    QUOTEKEY = ...
    RETKEY = ...
    RIGHTALTKEY = ...
    RIGHTARROWKEY = ...
    RIGHTBRACKETKEY = ...
    RIGHTCTRLKEY = ...
    RIGHTMOUSE = ...
    RIGHTSHIFTKEY = ...
    RKEY = ...
    SEMICOLONKEY = ...
    SEVENKEY = ...
    SIXKEY = ...
    SKEY = ...
    SLASHKEY = ...
    SPACEKEY = ...
    TABKEY = ...
    THREEKEY = ...
    TKEY = ...
    TWOKEY = ...
    UKEY = ...
    UPARROWKEY = ...
    VKEY = ...
    WHEELDOWNMOUSE = ...
    WHEELUPMOUSE = ...
    WKEY = ...
    XKEY = ...
    YKEY = ...
    ZEROKEY = ...
    ZKEY = ...


class ButtonState(Enum):
    pressed = ...
    released = ...
    held = ...
    none = ...


class AudioDistanceModel(Enum):
    linear = ...
